### ISSUE TITLE
Cellular network not working [QUESTION] - <title>

### ISSUE THREAD

**Issue by siddu8296** [n00b69/woa-vayu#1]
### Question

In poco x3 pro cellular network not showing in both sim 1 and sim 2

### Agreement

- [X] I am asking a sensible question.
- [X] I am not trying to waste time.
- [X] There is no issue already describing my problem.

**Comment by n00b69** [comment]
Only SIM1 works, try:

1) Mount Windows in WOA Helper to check if mounting works. If it does,
2) Press Quickboot

**Comment by chilledsheep** [comment]
Same issue here. I have latest UEFI and Drivers installed.
Windows mounting in WOA Helper works, it also has successfully copied StA to it.
Windows shows IMEI Number and Dataclasses: GPRS; EDGE; UMTS; HSDPA; HSUPA; LTE, and Firmware: 1.0.c3-00205-566234.10507_1407 at the settings screen
but it always says "No Signal" when i insert the SIM Card. I have tested with 3 different SIMs from 3 different providers and all SIMs are working fine under Android.

**Comment by n00b69** [comment]
Seems like recent drivers have issues with LTE. It's a hit or miss whether it works or not.

The last time it was confirmed to work stable and reliably is a few months ago. I have a prebuilt Windows image with the old drivers preinstalled, in case you'd like to use LTE. It does not have SD support, though.

**Comment by chilledsheep** [comment]
i have updated from april drivers to latest in hope that Cellular will finally work because with april drivers it did not work either

**Comment by n00b69** [comment]
I'm not sure if this image has april drivers, but you can give it a try if you want. Use the "unified3.img" provided in the same archive.

https://drive.google.com/drive/folders/1bKwpZqe4NWqpppdQ7fuccIQBhJa3rYLf

**Comment by n00b69** [comment]
LTE should work on latest drivers (v2408.19), reopen the issue or open a new one if it doesn't
