### ISSUE TITLE
OTG cable not detected jast charging 

### ISSUE THREAD

**Issue by aabirroy351** [n00b69/woa-vayu#7]
### Description

My OTG cable is not being detected by my device; it only shows charging but otg cable is ok and mouse also. I have tried using the cable on other devices, but the issue persists. Please help me fix this  problem.

### Reproduction steps

```bash
Please help me and problem the solve only vayu phone
```

### Agreement

- [X] I am using the latest Drivers.
- [X] I am running Windows 11 On The Phone.
- [X] There is no issue already describing my problem.

**Comment by n00b69** [comment]
Try (re)enabling USB host mode. Use the script in the WOA Helper app or find it in the Troubleshooting guide.

**Comment by n00b69** [comment]
Closing assuming it got fixed
